### ISSUE TITLE
Select a tool--Greenfoot or Processing?

### ISSUE THREAD

**Issue by taogeng3** [judyyang40/SpinningPanda#6]
As two tools can be used, either Greenfoot or Processing, we have to select a tool to accomplish the finite state machine.

**Comment by judyyang40** [comment]
See if either Greenfoot or Processing supports unit testing

**Comment by qili0102** [comment]
Both Greenfoot and Processing do not have an unit test function, we can add a test class to the Actor manually.

**Comment by judyyang40** [comment]
Decided to go with Greenfoot
